networks:
  qa-la-net:
    driver: bridge
    name: qa-la-net

services:
  chrome:
    image: harbor.tid.es/proxy_cache/selenoid/chrome:112.0
    networks:
      - qa-la-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid_video:
    image: harbor.tid.es/proxy_cache/selenoid/video-recorder:latest-release
    networks:
      - qa-la-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid-ui:
    image: harbor.tid.es/proxy_cache/aerokube/selenoid-ui:latest
    networks:
      - qa-la-net
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  selenoid:
    image: harbor.tid.es/proxy_cache/aerokube/selenoid:latest
    networks:
      - qa-la-net
    volumes:
      - /dev/shm:/dev/shm
      - ./tests/tools/selenoid/config:/etc/selenoid:ro
      - ./tests/tools/selenoid/.video:/opt/selenoid/video
      - ./tests/tools/selenoid/.logs:/opt/selenoid/logs
      - "/var/run/docker.sock:/var/run/docker.sock"
    shm_size: 2g
    command: [
        "-conf", "/etc/selenoid/browsers.json",
        "-video-output-dir", "/opt/selenoid/video",
        "-log-output-dir", "/opt/selenoid/logs",
        "-session-attempt-timeout", "2m",
        "-service-startup-timeout", "2m",
        "-container-network", "qa-la-net"
    ]
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/tests/tools/selenoid/.video
      - DISPLAY=:99
    ports:
      - "4444:4444"
    depends_on:
      - chrome

  browsermob-proxy:
    image: browsermob_proxy
    build:
      context: .
      dockerfile: tests/tools/browsermob_proxy/Dockerfile
    networks:
      - qa-la-net
    ports:
      - "8080:8080"
      - "8082:8082"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  mock-server:
    command: sh -c "toolium mock-server --port 8889"
    networks:
      - qa-la-net
    expose:
      - "8889"
    ports:
      - "8889:8889"
    build:
      context: .
      dockerfile: tests/tools/mock/Dockerfile

  mock-server-new:
    image: harbor.tid.es/proxy_cache/mockserver/mockserver:latest
    networks:
      - qa-la-net
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
    volumes:
      - ./tests/tools/mock-server-new/mockserver.properties:/config/mockserver.properties
    expose:
      - "8091"
    ports:
      - "8091:8091"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - qa-la-net
    ports:
      - "3000:3000"

  la-qa-py-env:
    image: la-qa-py-env:latest
    build:
      context: .
      dockerfile: tests/acceptance/Dockerfile
      args:
        NEXUS_LA_USER: "${NEXUS_LA_USER}"
        NEXUS_LA_PASSWORD: "${NEXUS_LA_PASSWORD}"
    networks:
      - qa-la-net
    volumes:
      - ./tests/acceptance/:/app
      - ./tests/acceptance/_output:/app/_output
    environment:
      - AUTORETRY=${AUTORETRY:-}
      - DEMO_URL=${DEMO_URL:-}
      - FEATURES_FOLDER=${FEATURES_FOLDER:-components}
      - JIRA_BUILD=${JIRA_BUILD:-}
      - JIRA_COMPONENT=${JIRA_COMPONENT:-}
      - JIRA_EXTRA_LABELS=${JIRA_EXTRA_LABELS:-}
      - JIRA_ISSUE=${JIRA_ISSUE:-no_issue}
      - JIRA_QUERY=${JIRA_QUERY:-}
      - JIRA_REPORT=${JIRA_REPORT:-}
      - JIRA_TOKEN=${JIRA_TOKEN:-}
      - JIRA_VERSION=${JIRA_VERSION:-}
      - LANGUAGE=${LANGUAGE:-}
      - PR_NUMBER=${PR_NUMBER:-}
      - PRIORITY=${PRIORITY:-}
      - TAGS=${TAGS:-no_tag}
      - TEST_ENV=${TEST_ENV:-}
      - USER_TEST=${USER_TEST:-}
    command: tail -f /dev/null
