networks:
  docker-net:
    driver: bridge
    name: docker-net

services:
  chrome:
    image: selenoid/chrome:98.0
    networks:
      - docker-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid_video:
    image: selenoid/video-recorder:latest-release
    networks:
      - docker-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    networks:
      - docker-net
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  selenoid:
    image: aerokube/selenoid:latest
    networks:
      - docker-net
    volumes:
      - /dev/shm:/dev/shm
      - ./tests/tools/selenoid/config:/etc/selenoid:ro
      - ./tests/tools/selenoid/.video:/opt/selenoid/video
      - ./tests/tools/selenoid/.logs:/opt/selenoid/logs
      - "/var/run/docker.sock:/var/run/docker.sock"
    shm_size: 2g
    command: [
        "-conf", "/etc/selenoid/browsers.json",
        "-video-output-dir", "/opt/selenoid/video",
        "-log-output-dir", "/opt/selenoid/logs",
        "-session-attempt-timeout", "2m",
        "-service-startup-timeout", "2m",
        "-container-network", "docker-net"
    ]
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: $PWD/tests/tools/selenoid/.video
    ports:
      - "4444:4444"
    depends_on:
      - chrome
      - selenoid-ui

  browsermob-proxy:
    image: browsermob_proxy
    build:
      context: .
      dockerfile: tests/tools/browsermob_proxy/Dockerfile
    networks:
      - docker-net
    ports:
      - "8080:8080"
      - "8082:8082"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - docker-net
    ports:
      - "3000:3000"

  acceptance-tests: &acceptance_tests
    image: local/docker-net:latest
    build:
      context: .
      dockerfile: tests/acceptance/Dockerfile
      args:
        NEXUS_USER: ${NEXUS_USER}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
    networks:
      - docker-net
    volumes:
      - ./tests/acceptance/:/app

  docker-tests:
    <<: *acceptance_tests
    environment:
      - PROJECT=${PROJECT}
      - TEST_ENV=${TEST_ENV:-es-dev}
      - PRIORITY=${PRIORITY:-smoke}
      - JIRA_ISSUE=${JIRA_ISSUE:-no_issue}
      - JIRA_VERSION=${JIRA_VERSION:-no_version}
      - JIRA_BUILD=${JIRA_BUILD:-Release}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - JIRA_LABELS=${JIRA_LABELS:-automatic}
      - AUTORETRY=${AUTORETRY:-true}
      - TAGS=${TAGS:-no_tag}
      - FEATURES_FOLDER=${FEATURES_FOLDER:-components}
      - USER_TEST=${USER_TEST:-user_ci}
      - PR_NUMBER=${PR_NUMBER}
    command:
      - /bin/bash
      - -c
      - |
        wait-for-it --service browsermob-proxy:8080 --timeout=120 -- &&
        wait-for-it --service selenoid:4444 --timeout=120 -- &&
        ./scripts/run_tests.sh
    depends_on:
      - selenoid
      - browsermob-proxy
