services:
  features-checks:
    image: la-qa-commons:latest
    environment:
      - JIRA_TOKEN=${JIRA_TOKEN}
    build:
      context: .
      dockerfile: tests/acceptance/Dockerfile
      args:
        NEXUS_USER: ${NEXUS_USER}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
    volumes:
      - ./tests/acceptance:/app/
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        laqacommons review-duplicated-ids -f features/ 2> /app/errors_1.txt
        if [ -s /app/errors_1.txt ]; then
          cat /app/errors_1.txt
          exit 1
        fi
        laqacommons list-jira-bugs -f features/ -s "'Closed','Resolved'" 2> /app/errors_2.txt
        if [ -s /app/errors_2.txt ]; then
          cat /app/errors_2.txt
          exit 1
        fi
