name: Run QA acceptance tests

on:
  workflow_call:
    inputs:
      app-env:
        required: true
        type: string
        default: es-qa
      priority:
        required: true
        type: string
        default: smoke
      filter-tags:
        required: false
        type: string
      jira-report:
        type: boolean
        required: false
        default: false
      jira-issue:
        type: string
        required: false
        default: no_issue
      jira-executed-version:
        required: false
        type: string
        default: CI
      jira-build:
        required: false
        type: string
        default: Release
      jira-extra-labels:
        required: false
        type: string
      filter-folders:
        required: false
        type: string
        default: "components, e2e, integration"
      max-parallel:
        required: false
        type: number
        default: 1
      demo-url:
        required: false
        type: string

  workflow_dispatch:
    inputs:
      app-env:
        description: 'Select the environment'
        required: true
        type: choice
        default: es-qa
        options:
          - es-qa
          - es-dev
          - br-qa
      priority:
        description: 'Select the runner type'
        required: true
        type: choice
        default: regression
        options:
          - regression
          - sanity
          - smoke
      filter-tags:
        description: 'Scenario tags (Use "," for OR condition. Use ";" for AND condition)'
        required: false
        type: string
        default: no_tag
      jira-report:
        description: 'JIRA report. Report the test results in JIRA'
        type: boolean
        required: true
        default: false
      jira-executed-version:
        description: 'Select the Jira execution version.'
        required: false
        type: choice
        default: CI
        options:
          - CI
          - v3.29_Ceres
          - v3.30_Dandara
      jira-build:
        description: 'Select the build'
        required: false
        type: choice
        default: Release
        options:
          - Release
          - rc1
          - rc2
          - rc3
      jira-extra-labels:
        description: 'Labels separated by "," to be added in the Jira execution, the value date is replaced by the current date'
        required: false
        type: string
      filter-folders:
        description: 'Select the filters folder to be executed'
        required: false
        type: string
        default: "components, e2e, integration"
      max-parallel:
        description: 'Maximun parallel jobs' 
        required: false
        type: choice
        default: "2"
        options:
          - "1"
          - "2"
          - "3"
          - "4"
      demo-url:
        description: 'Living App Url to run the tests'
        required: false
        type: string

jobs:
  run-acceptance-tests:
    name: Run ${{ inputs.priority }} tests
    uses: Telefonica/living-apps-gh-actions/.github/workflows/qa-run-tests.yaml@master
    with:
      app-env: "${{ inputs.app-env }}"
      priority: "${{ inputs.priority }}"
      user-test: "default"
      deploy-up-command: "make docker-up"
      filter-tags: "${{ inputs.filter-tags }}"
      filter-folders: "${{ inputs.filter-folders }}"
      jira-component: "<Living APP COMPONENT IN JIRA>"
      jira-executed-version: "${{ inputs.jira-executed-version }}"
      jira-extra-labels: "${{ inputs.jira-extra-labels }}"
      jira-report: "${{ inputs.jira-report }}"
      jira-build: "${{ inputs.jira-build }}"
      jira-issue: "${{ inputs.jira-issue }}"
      max-parallel: "${{ inputs.max-parallel }}"
      demo-url: "${{ inputs.demo-url }}"
      send-email: false
    secrets: inherit
