name: QA PullRequest

on:
  pull_request:
    paths:
      - 'tests/acceptance/**'
      - 'docker-compose.qa.yaml'
      - '.github/workflows/qa-*.yaml'

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
  get-title-jira-issue:
    name: Get jira issue from pr title
    runs-on: ${{ vars.QA_RUNNER }}
    outputs:
      issue: ${{ steps.get_issue.outputs.jira_id }}
    steps:
      - name: Get title issue
        continue-on-error: true
        id: get_issue
        uses: Telefonica/qacdco-github-actions/utilities/jira/get-jira-id@main

  pr-sanity:
    name: Sanity ${{ needs.get-title-jira-issue.outputs.issue }}
    needs: [get-title-jira-issue]
    uses: ./.github/workflows/qa-acceptance-tests.yaml
    with:
      priority: sanity
      jira-issue: ${{ needs.get-title-jira-issue.outputs.issue }}
    secrets: inherit

  feature-checks:
    name: Feature checks
    uses: Telefonica/living-apps-gh-actions/.github/workflows/qa-pull-request-checks.yaml@chore-unificate-qa-workflows
    secrets: inherit
